In [ ]:
# MY lackings:
#iLOC, data slicing

In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pickle

In [ ]:
df = pd.read_csv("/content/diabetes_train.csv")

In [ ]:
df.head()

id  Pregnancies  Glucose  ...  DiabetesPedigreeFunction  Age  Outcome
0  1129            2      100  ...                     0.368   21        0
1  1598            3       99  ...                     0.154   24        0
2   726           12       88  ...                     0.378   48        0
3   632            4      122  ...                     0.394   29        0
4  1748            1      181  ...                     1.258   22        1

[5 rows x 10 columns]

In [ ]:
df.drop(['id'], axis=1,inplace=True)

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            2      100             64  ...                     0.368   21        0
1            3       99             54  ...                     0.154   24        0
2           12       88             74  ...                     0.378   48        0
3            4      122             68  ...                     0.394   29        0
4            1      181             78  ...                     1.258   22        1

[5 rows x 9 columns]

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X = df.iloc[:,0:8].values

In [ ]:
X

array([[2.00e+00, 1.00e+02, 6.40e+01, ..., 2.97e+01, 3.68e-01, 2.10e+01],
       [3.00e+00, 9.90e+01, 5.40e+01, ..., 2.56e+01, 1.54e-01, 2.40e+01],
       [1.20e+01, 8.80e+01, 7.40e+01, ..., 3.53e+01, 3.78e-01, 4.80e+01],
       ...,
       [8.00e+00, 1.94e+02, 8.00e+01, ..., 2.61e+01, 5.51e-01, 6.70e+01],
       [5.00e+00, 1.32e+02, 8.00e+01, ..., 2.68e+01, 1.86e-01, 6.90e+01],
       [4.00e+00, 1.18e+02, 7.00e+01, ..., 4.45e+01, 9.04e-01, 2.60e+01]])

In [ ]:
X.shape

(1500, 8)

In [ ]:
Y = df.iloc[:,8].values

In [ ]:
Y

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [ ]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((1200, 8), (300, 8), (1200,), (300,))

In [ ]:
S = StandardScaler()
X_train = S.fit_transform(X_train)
X_test = S.fit_transform(X_test)

In [ ]:
X_test

array([[ 0.31268883,  0.76526645,  0.6641245 , ...,  0.09157133,
        -0.01789908,  1.86907185],
       [-0.88230033,  0.3097507 ,  0.10236506, ..., -0.61134618,
         0.04918054, -0.93687421],
       [ 0.01394154, -0.08069136,  0.10236506, ...,  1.53197606,
         1.4981002 , -0.62510243],
       ...,
       [-0.88230033, -1.60992278, -0.27214124, ..., -1.08379893,
        -0.13864238, -0.62510243],
       [ 1.2089307 , -0.50367026,  1.50676368, ...,  1.39369721,
        -0.73229697,  0.85581355],
       [ 1.50767799, -0.27591239,  0.6641245 , ..., -0.34631171,
         2.76590491,  1.24552828]])

In [ ]:
model = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
model.fit(X_train,Y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred =model.predict(X_test)

In [ ]:
Conf_metric = confusion_matrix(Y_test,y_pred)

In [ ]:
ACC_metric = accuracy_score(Y_test,y_pred)

In [ ]:
with open('Diabetes_pickle.pkl','wb') as f:
  pickle.dump(model,f)

In [ ]:
with open('Diabetes_pickle.pkl','rb') as f:
  m =pickle.load(f)